// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL60AyB4BhCq8KADBh62_YptQ5ph8CDMQ',
    appId: '1:941039710349:web:e1a4752ce8643963d932c4',
    messagingSenderId: '941039710349',
    projectId: 'blog-fire-1f3d7',
    authDomain: 'blog-fire-1f3d7.firebaseapp.com',
    storageBucket: 'blog-fire-1f3d7.appspot.com',
    measurementId: 'G-0CZQX4EG5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEZu2kg-UbDWQGCW6dRx_wcSXy7wD05yg',
    appId: '1:941039710349:android:16b37cc44246a752d932c4',
    messagingSenderId: '941039710349',
    projectId: 'blog-fire-1f3d7',
    storageBucket: 'blog-fire-1f3d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhXRyl8AecmHDWULp0gi13tlor7BcN-ak',
    appId: '1:941039710349:ios:85b383e01513a4bfd932c4',
    messagingSenderId: '941039710349',
    projectId: 'blog-fire-1f3d7',
    storageBucket: 'blog-fire-1f3d7.appspot.com',
    iosBundleId: 'com.example.blogFire',
  );
}
